/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-vosk.h
 #	source generated by 4D Plugin Wizard
 #	Project : vosk
 #	author : miyako
 #	2025/06/14
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_VOSK_H
#define PLUGIN_VOSK_H

#include "4DPluginAPI.h"
#include "C_TEXT.h"
#include "vosk_api.h"
#include "4DPlugin-JSON.h"
#include "json.h"

#include <time.h>
#include <mutex>
#include <chrono>
#include <stdio.h>

#include "portaudio.h"
#define DR_WAV_IMPLEMENTATION
#include "dr_wav.h"

typedef struct {
    drwav wav;
    void* pWavData;
    size_t wavDataSize;
    std::vector<char> buf;
    size_t pos;
} UserData;

#pragma mark -

void vosk(PA_PluginParameters params);

#endif /* PLUGIN_VOSK_H */
